# Generated by Django 3.0.7 on 2020-06-24 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('display_picture', models.ImageField(blank=True, default='none.png', null=True, upload_to='')),
                ('news_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsTypes')),
            ],
        ),
    ]
