# Generated by Django 3.0.7 on 2020-06-29 06:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.IntegerField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('display_picture', models.ImageField(blank=True,
                                                      default='image_placeholder.png', null=True, upload_to='')),
                ('editor', models.CharField(default='SahayogiNews', max_length=100)),
                ('pub_date', models.DateTimeField(
                    default=datetime.datetime(2020, 6, 29, 11, 52, 21, 95320))),
                ('news_type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.NewsType')),
            ],
        ),
    ]
