# Generated by Django 3.0.8 on 2020-07-01 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200629_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body_eng',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='editor_eng',
            field=models.CharField(default='Sahayogi News', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='title_eng',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='newstype',
            name='title_eng',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='editor',
            field=models.CharField(default='सहयोगी समाचार ', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 14, 10, 4, 660982)),
        ),
        migrations.AlterField(
            model_name='newstype',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
