# Generated by Django 3.0.7 on 2020-06-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200624_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='editor',
            field=models.CharField(default='SahayogiNews', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
