# Generated by Django 3.0.8 on 2020-07-01 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200701_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 14, 17, 38, 328250)),
        ),
        migrations.AlterField(
            model_name='newstype',
            name='title_eng',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
