# Generated by Django 3.0.7 on 2020-06-25 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200625_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='display_picture',
            field=models.ImageField(default='image.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.NewsType'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 14, 7, 57, 125874)),
        ),
    ]
