# Generated by Django 3.0.8 on 2020-07-01 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200701_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 14, 25, 16, 69664)),
        ),
        migrations.AlterField(
            model_name='newstype',
            name='title',
            field=models.CharField(default='समाचार को प्रकार', max_length=100, verbose_name='समाचार को प्रकार'),
        ),
        migrations.AlterField(
            model_name='newstype',
            name='title_eng',
            field=models.CharField(default='Type Of News ', max_length=100, verbose_name='Type Of News'),
        ),
    ]
