# Generated by Django 3.0.7 on 2020-06-26 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200625_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='display_picture',
            field=models.ImageField(blank=True, default='image.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 11, 45, 34, 708524)),
        ),
    ]
