# Generated by Django 3.0.8 on 2020-07-01 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200701_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.URLField()),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='description_eng',
            field=models.TextField(default='No description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 17, 46, 29, 85009)),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='शिर्षक भेटिएन', max_length=250, verbose_name='शिर्षक'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_eng',
            field=models.CharField(default='No Title', max_length=250, null=True, verbose_name='Title'),
        ),
    ]
