# Generated by Django 3.0.8 on 2020-07-16 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200716_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.URLField()),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('darta_no', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.AlterField(
            model_name='developersinfo',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='developersinfo',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 22, 59, 19, 718277)),
        ),
    ]
