# Generated by Django 3.0.8 on 2020-07-16 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200716_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='contact',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='organization_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='organization_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 23, 28, 57, 345308)),
        ),
    ]
