# Generated by Django 3.0.8 on 2020-07-23 14:21

import datetime
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20200716_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=djrichtextfield.models.RichTextField(default='विवरण भेटिएन', verbose_name='विवरण'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_eng',
            field=djrichtextfield.models.RichTextField(default='No description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 20, 6, 30, 307131)),
        ),
    ]
