# Generated by Django 3.0.8 on 2020-07-23 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20200723_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='chief_editor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 22, 22, 8, 514950)),
        ),
    ]
