# Generated by Django 3.0.8 on 2020-07-23 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20200723_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='editor',
            field=models.CharField(default='सौम्य समाचार', max_length=100, verbose_name='सम्पादक'),
        ),
        migrations.AlterField(
            model_name='news',
            name='editor_eng',
            field=models.CharField(default='Saumya News', max_length=100, verbose_name='Editor'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 22, 33, 9, 35769)),
        ),
    ]
