# Generated by Django 3.0.8 on 2020-08-04 07:20

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20200804_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='विवरण भेटिएन', verbose_name='विवरण'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_eng',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='No description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 13, 5, 6, 721799)),
        ),
    ]
